# This template incomplete and only used for GitHub Code Scanning
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  Function:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      CodeUri: ./src
