name: "Code Scanning - Action"

on:
  push:
    branches:
      - dvcsharp-api-buildless
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
          - csharp

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/${{ matrix.language }}-config.yml
          # queries: security-extended
          # queries: security-and-quality

          # "Please make sure that every branch in on.pull_request is also in on.push so that Code Scanning can compare pull requests against the state of the base branch."
          # packs: codeql/javascript-experimental-atm-queries

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        if: ${{ matrix.language == 'csharp' }}
        uses: github/codeql-action/autobuild@v2
        # env:
        #   CODEQL_EXTRACTOR_CSHARP_OPTION_BUILDLESS: true

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #     make bootstrap
      #     make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
